CREATE SCHEMA IF NOT EXISTS mvbl
  AUTHORIZATION kv_admin;

GRANT ALL ON SCHEMA mvbl TO kv_admin;
GRANT USAGE ON SCHEMA mvbl TO kv_user;
COMMENT ON SCHEMA mvbl
  IS 'Schema für die MVBL-Applikation';

ALTER DEFAULT PRIVILEGES IN SCHEMA mvbl
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO kv_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA mvbl
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO kv_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA mvbl
    GRANT EXECUTE ON FUNCTIONS
    TO kv_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA mvbl
    GRANT USAGE ON TYPES
    TO kv_user;
